require "user.options"
require "user.plugins"
require "user.tokyodark"
require "user.tokyonight"
require "user.catppuccin"
require "user.moonfly"
require "user.nightfly"
require "user.citruszest"
require "user.colorscheme"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.focus"
require "user.treesitter"
require "user.indent-blankline"
require "user.trouble"
require "user.cmp"
--require "user.markdown-preview"  -- todo
